title: Berke Lunstad
url: https://blog.berkelunstad.com
permalink: /:title/
plugins:
  - jekyll-feed
exclude:
  - docs
  - README.md
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
